import "./globals.css";
export const metadata = {
  title: "BIOARECA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/arecalogos.png" />
      </head>
      <body>{children}</body>
    </html>
  );
}
